{
//=========Macro generated from canvas: AllExtFlights/AllExtFlights
//=========  (Tue Oct 31 13:11:01 2017) by ROOT version5.34/14
   TCanvas *AllExtFlights = new TCanvas("AllExtFlights", "AllExtFlights",0,50,1200,500);
   gStyle->SetOptTitle(0);
   AllExtFlights->SetHighLightColor(2);
   AllExtFlights->Range(0,0,1,1);
   AllExtFlights->SetFillColor(0);
   AllExtFlights->SetBorderMode(0);
   AllExtFlights->SetBorderSize(2);
   AllExtFlights->SetLeftMargin(0.15);
   AllExtFlights->SetBottomMargin(0.15);
   AllExtFlights->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: AllExtFlights_1
   TPad *AllExtFlights_1 = new TPad("AllExtFlights_1", "AllExtFlights_1",0.01,0.51,0.3233333,0.99);
   AllExtFlights_1->Draw();
   AllExtFlights_1->cd();
   AllExtFlights_1->Range(-75,-0.9619281,425,3.444059);
   AllExtFlights_1->SetFillColor(0);
   AllExtFlights_1->SetBorderMode(0);
   AllExtFlights_1->SetBorderSize(2);
   AllExtFlights_1->SetLogy();
   AllExtFlights_1->SetGridx();
   AllExtFlights_1->SetGridy();
   AllExtFlights_1->SetLeftMargin(0.15);
   AllExtFlights_1->SetBottomMargin(0.15);
   AllExtFlights_1->SetFrameBorderMode(0);
   AllExtFlights_1->SetFrameBorderMode(0);
   
   TH1D *Dots = new TH1D("Dots","Dots",100,0,375);
   Dots->SetBinContent(2,532);
   Dots->SetBinContent(3,268);
   Dots->SetBinContent(4,202);
   Dots->SetBinContent(5,218);
   Dots->SetBinContent(6,158);
   Dots->SetBinContent(7,130);
   Dots->SetBinContent(8,128);
   Dots->SetBinContent(9,104);
   Dots->SetBinContent(10,91);
   Dots->SetBinContent(11,98);
   Dots->SetBinContent(12,80);
   Dots->SetBinContent(13,81);
   Dots->SetBinContent(14,105);
   Dots->SetBinContent(15,98);
   Dots->SetBinContent(16,79);
   Dots->SetBinContent(17,141);
   Dots->SetBinContent(18,119);
   Dots->SetBinContent(19,111);
   Dots->SetBinContent(20,63);
   Dots->SetBinContent(21,68);
   Dots->SetBinContent(22,62);
   Dots->SetBinContent(23,52);
   Dots->SetBinContent(24,24);
   Dots->SetBinContent(25,34);
   Dots->SetBinContent(26,26);
   Dots->SetBinContent(27,18);
   Dots->SetBinContent(28,16);
   Dots->SetBinContent(29,15);
   Dots->SetBinContent(30,17);
   Dots->SetBinContent(31,8);
   Dots->SetBinContent(32,9);
   Dots->SetBinContent(33,7);
   Dots->SetBinContent(34,7);
   Dots->SetBinContent(35,6);
   Dots->SetBinContent(36,3);
   Dots->SetBinContent(37,6);
   Dots->SetBinContent(38,6);
   Dots->SetBinContent(39,7);
   Dots->SetBinContent(40,6);
   Dots->SetBinContent(41,3);
   Dots->SetBinContent(42,2);
   Dots->SetBinContent(43,1);
   Dots->SetBinContent(44,1);
   Dots->SetBinContent(45,4);
   Dots->SetBinContent(46,3);
   Dots->SetBinContent(47,7);
   Dots->SetBinContent(48,2);
   Dots->SetBinContent(49,1);
   Dots->SetBinContent(52,1);
   Dots->SetBinContent(62,1);
   Dots->SetBinContent(74,1);
   Dots->SetBinContent(101,16170);
   Dots->SetEntries(1750);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("Dots");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 1750   ");
   text = ptstats->AddText("Mean  =   38.9");
   text = ptstats->AddText("RMS   =  32.83");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   Dots->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(Dots);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#00cc66");
   Dots->SetLineColor(ci);

   ci = TColor::GetColor("#00cc66");
   Dots->SetMarkerColor(ci);
   Dots->SetMarkerStyle(20);
   Dots->GetXaxis()->SetTitle("E [keV]");
   Dots->GetXaxis()->SetLabelFont(42);
   Dots->GetXaxis()->SetLabelSize(0.035);
   Dots->GetXaxis()->SetTitleSize(0.035);
   Dots->GetXaxis()->SetTitleFont(42);
   Dots->GetYaxis()->SetTitle("events");
   Dots->GetYaxis()->SetLabelFont(42);
   Dots->GetYaxis()->SetLabelSize(0.035);
   Dots->GetYaxis()->SetTitleSize(0.035);
   Dots->GetYaxis()->SetTitleFont(42);
   Dots->GetZaxis()->SetLabelFont(42);
   Dots->GetZaxis()->SetLabelSize(0.035);
   Dots->GetZaxis()->SetTitleSize(0.035);
   Dots->GetZaxis()->SetTitleFont(42);
   Dots->Draw("colz");
   AllExtFlights_1->Modified();
   AllExtFlights->cd();
  
// ------------>Primitives in pad: AllExtFlights_2
   AllExtFlights_2 = new TPad("AllExtFlights_2", "AllExtFlights_2",0.3433333,0.51,0.6566667,0.99);
   AllExtFlights_2->Draw();
   AllExtFlights_2->cd();
   AllExtFlights_2->Range(-3000,-0.5565398,17000,1.146859);
   AllExtFlights_2->SetFillColor(0);
   AllExtFlights_2->SetBorderMode(0);
   AllExtFlights_2->SetBorderSize(2);
   AllExtFlights_2->SetLogy();
   AllExtFlights_2->SetGridx();
   AllExtFlights_2->SetGridy();
   AllExtFlights_2->SetLeftMargin(0.15);
   AllExtFlights_2->SetBottomMargin(0.15);
   AllExtFlights_2->SetFrameBorderMode(0);
   AllExtFlights_2->SetFrameBorderMode(0);
   
   TH1D *HeavyBlobs = new TH1D("HeavyBlobs","HeavyBlobs",100,0,15000);
   HeavyBlobs->SetBinContent(3,2);
   HeavyBlobs->SetBinContent(6,2);
   HeavyBlobs->SetBinContent(8,2);
   HeavyBlobs->SetBinContent(9,2);
   HeavyBlobs->SetBinContent(10,4);
   HeavyBlobs->SetBinContent(11,5);
   HeavyBlobs->SetBinContent(13,2);
   HeavyBlobs->SetBinContent(14,3);
   HeavyBlobs->SetBinContent(15,1);
   HeavyBlobs->SetBinContent(16,3);
   HeavyBlobs->SetBinContent(17,5);
   HeavyBlobs->SetBinContent(21,1);
   HeavyBlobs->SetBinContent(22,3);
   HeavyBlobs->SetBinContent(23,1);
   HeavyBlobs->SetBinContent(24,1);
   HeavyBlobs->SetBinContent(25,2);
   HeavyBlobs->SetBinContent(26,1);
   HeavyBlobs->SetBinContent(27,1);
   HeavyBlobs->SetBinContent(28,2);
   HeavyBlobs->SetBinContent(30,2);
   HeavyBlobs->SetBinContent(32,1);
   HeavyBlobs->SetBinContent(33,1);
   HeavyBlobs->SetBinContent(41,1);
   HeavyBlobs->SetBinContent(42,1);
   HeavyBlobs->SetBinContent(44,1);
   HeavyBlobs->SetBinContent(45,1);
   HeavyBlobs->SetBinContent(56,1);
   HeavyBlobs->SetBinContent(60,1);
   HeavyBlobs->SetBinContent(72,1);
   HeavyBlobs->SetBinContent(85,1);
   HeavyBlobs->SetBinContent(100,2);
   HeavyBlobs->SetBinContent(101,268);
   HeavyBlobs->SetEntries(317);
   
   ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   text = ptstats->AddText("HeavyBlobs");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 317    ");
   text = ptstats->AddText("Mean  =   3687");
   text = ptstats->AddText("RMS   =   3263");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   HeavyBlobs->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(HeavyBlobs);

   ci = TColor::GetColor("#cc6600");
   HeavyBlobs->SetLineColor(ci);

   ci = TColor::GetColor("#cc6600");
   HeavyBlobs->SetMarkerColor(ci);
   HeavyBlobs->SetMarkerStyle(21);
   HeavyBlobs->GetXaxis()->SetTitle("E [keV]");
   HeavyBlobs->GetXaxis()->SetLabelFont(42);
   HeavyBlobs->GetXaxis()->SetLabelSize(0.035);
   HeavyBlobs->GetXaxis()->SetTitleSize(0.035);
   HeavyBlobs->GetXaxis()->SetTitleFont(42);
   HeavyBlobs->GetYaxis()->SetTitle("events");
   HeavyBlobs->GetYaxis()->SetLabelFont(42);
   HeavyBlobs->GetYaxis()->SetLabelSize(0.035);
   HeavyBlobs->GetYaxis()->SetTitleSize(0.035);
   HeavyBlobs->GetYaxis()->SetTitleFont(42);
   HeavyBlobs->GetZaxis()->SetLabelFont(42);
   HeavyBlobs->GetZaxis()->SetLabelSize(0.035);
   HeavyBlobs->GetZaxis()->SetTitleSize(0.035);
   HeavyBlobs->GetZaxis()->SetTitleFont(42);
   HeavyBlobs->Draw("colz");
   AllExtFlights_2->Modified();
   AllExtFlights->cd();
  
// ------------>Primitives in pad: AllExtFlights_3
   AllExtFlights_3 = new TPad("AllExtFlights_3", "AllExtFlights_3",0.6766667,0.51,0.99,0.99);
   AllExtFlights_3->Draw();
   AllExtFlights_3->cd();
   AllExtFlights_3->Range(-300,-0.9999312,1700,3.65941);
   AllExtFlights_3->SetFillColor(0);
   AllExtFlights_3->SetBorderMode(0);
   AllExtFlights_3->SetBorderSize(2);
   AllExtFlights_3->SetLogy();
   AllExtFlights_3->SetGridx();
   AllExtFlights_3->SetGridy();
   AllExtFlights_3->SetLeftMargin(0.15);
   AllExtFlights_3->SetBottomMargin(0.15);
   AllExtFlights_3->SetFrameBorderMode(0);
   AllExtFlights_3->SetFrameBorderMode(0);
   
   TH1D *CurlyTracks = new TH1D("CurlyTracks","CurlyTracks",100,0,1500);
   CurlyTracks->SetBinContent(2,5);
   CurlyTracks->SetBinContent(3,6);
   CurlyTracks->SetBinContent(4,26);
   CurlyTracks->SetBinContent(5,148);
   CurlyTracks->SetBinContent(6,464);
   CurlyTracks->SetBinContent(7,779);
   CurlyTracks->SetBinContent(8,824);
   CurlyTracks->SetBinContent(9,725);
   CurlyTracks->SetBinContent(10,534);
   CurlyTracks->SetBinContent(11,506);
   CurlyTracks->SetBinContent(12,411);
   CurlyTracks->SetBinContent(13,355);
   CurlyTracks->SetBinContent(14,362);
   CurlyTracks->SetBinContent(15,309);
   CurlyTracks->SetBinContent(16,244);
   CurlyTracks->SetBinContent(17,236);
   CurlyTracks->SetBinContent(18,199);
   CurlyTracks->SetBinContent(19,188);
   CurlyTracks->SetBinContent(20,144);
   CurlyTracks->SetBinContent(21,146);
   CurlyTracks->SetBinContent(22,130);
   CurlyTracks->SetBinContent(23,87);
   CurlyTracks->SetBinContent(24,88);
   CurlyTracks->SetBinContent(25,86);
   CurlyTracks->SetBinContent(26,73);
   CurlyTracks->SetBinContent(27,83);
   CurlyTracks->SetBinContent(28,57);
   CurlyTracks->SetBinContent(29,54);
   CurlyTracks->SetBinContent(30,48);
   CurlyTracks->SetBinContent(31,38);
   CurlyTracks->SetBinContent(32,41);
   CurlyTracks->SetBinContent(33,38);
   CurlyTracks->SetBinContent(34,37);
   CurlyTracks->SetBinContent(35,24);
   CurlyTracks->SetBinContent(36,32);
   CurlyTracks->SetBinContent(37,34);
   CurlyTracks->SetBinContent(38,29);
   CurlyTracks->SetBinContent(39,26);
   CurlyTracks->SetBinContent(40,18);
   CurlyTracks->SetBinContent(41,13);
   CurlyTracks->SetBinContent(42,16);
   CurlyTracks->SetBinContent(43,21);
   CurlyTracks->SetBinContent(44,19);
   CurlyTracks->SetBinContent(45,16);
   CurlyTracks->SetBinContent(46,11);
   CurlyTracks->SetBinContent(47,10);
   CurlyTracks->SetBinContent(48,10);
   CurlyTracks->SetBinContent(49,9);
   CurlyTracks->SetBinContent(50,9);
   CurlyTracks->SetBinContent(51,6);
   CurlyTracks->SetBinContent(52,11);
   CurlyTracks->SetBinContent(53,8);
   CurlyTracks->SetBinContent(54,9);
   CurlyTracks->SetBinContent(55,13);
   CurlyTracks->SetBinContent(56,6);
   CurlyTracks->SetBinContent(57,5);
   CurlyTracks->SetBinContent(58,8);
   CurlyTracks->SetBinContent(59,7);
   CurlyTracks->SetBinContent(60,7);
   CurlyTracks->SetBinContent(61,5);
   CurlyTracks->SetBinContent(62,7);
   CurlyTracks->SetBinContent(63,6);
   CurlyTracks->SetBinContent(64,5);
   CurlyTracks->SetBinContent(65,8);
   CurlyTracks->SetBinContent(66,6);
   CurlyTracks->SetBinContent(67,4);
   CurlyTracks->SetBinContent(68,4);
   CurlyTracks->SetBinContent(69,5);
   CurlyTracks->SetBinContent(70,1);
   CurlyTracks->SetBinContent(71,3);
   CurlyTracks->SetBinContent(72,4);
   CurlyTracks->SetBinContent(73,5);
   CurlyTracks->SetBinContent(74,6);
   CurlyTracks->SetBinContent(75,6);
   CurlyTracks->SetBinContent(76,5);
   CurlyTracks->SetBinContent(77,4);
   CurlyTracks->SetBinContent(78,4);
   CurlyTracks->SetBinContent(79,8);
   CurlyTracks->SetBinContent(80,5);
   CurlyTracks->SetBinContent(81,5);
   CurlyTracks->SetBinContent(82,3);
   CurlyTracks->SetBinContent(83,4);
   CurlyTracks->SetBinContent(84,4);
   CurlyTracks->SetBinContent(85,2);
   CurlyTracks->SetBinContent(86,1);
   CurlyTracks->SetBinContent(87,2);
   CurlyTracks->SetBinContent(88,2);
   CurlyTracks->SetBinContent(89,1);
   CurlyTracks->SetBinContent(91,4);
   CurlyTracks->SetBinContent(92,2);
   CurlyTracks->SetBinContent(93,3);
   CurlyTracks->SetBinContent(96,1);
   CurlyTracks->SetBinContent(97,2);
   CurlyTracks->SetBinContent(98,1);
   CurlyTracks->SetBinContent(100,1);
   CurlyTracks->SetBinContent(101,42659);
   CurlyTracks->SetEntries(7879);
   
   ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   text = ptstats->AddText("CurlyTracks");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 7879   ");
   text = ptstats->AddText("Mean  =  223.4");
   text = ptstats->AddText("RMS   =  182.8");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   CurlyTracks->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(CurlyTracks);

   ci = TColor::GetColor("#009900");
   CurlyTracks->SetLineColor(ci);

   ci = TColor::GetColor("#009900");
   CurlyTracks->SetMarkerColor(ci);
   CurlyTracks->SetMarkerStyle(23);
   CurlyTracks->GetXaxis()->SetTitle("E [keV]");
   CurlyTracks->GetXaxis()->SetLabelFont(42);
   CurlyTracks->GetXaxis()->SetLabelSize(0.035);
   CurlyTracks->GetXaxis()->SetTitleSize(0.035);
   CurlyTracks->GetXaxis()->SetTitleFont(42);
   CurlyTracks->GetYaxis()->SetTitle("events");
   CurlyTracks->GetYaxis()->SetLabelFont(42);
   CurlyTracks->GetYaxis()->SetLabelSize(0.035);
   CurlyTracks->GetYaxis()->SetTitleSize(0.035);
   CurlyTracks->GetYaxis()->SetTitleFont(42);
   CurlyTracks->GetZaxis()->SetLabelFont(42);
   CurlyTracks->GetZaxis()->SetLabelSize(0.035);
   CurlyTracks->GetZaxis()->SetTitleSize(0.035);
   CurlyTracks->GetZaxis()->SetTitleFont(42);
   CurlyTracks->Draw("colz");
   AllExtFlights_3->Modified();
   AllExtFlights->cd();
  
// ------------>Primitives in pad: AllExtFlights_4
   AllExtFlights_4 = new TPad("AllExtFlights_4", "AllExtFlights_4",0.01,0.01,0.3233333,0.49);
   AllExtFlights_4->Draw();
   AllExtFlights_4->cd();
   AllExtFlights_4->Range(-1000,-0.6769518,5666.667,1.829193);
   AllExtFlights_4->SetFillColor(0);
   AllExtFlights_4->SetBorderMode(0);
   AllExtFlights_4->SetBorderSize(2);
   AllExtFlights_4->SetLogy();
   AllExtFlights_4->SetGridx();
   AllExtFlights_4->SetGridy();
   AllExtFlights_4->SetLeftMargin(0.15);
   AllExtFlights_4->SetBottomMargin(0.15);
   AllExtFlights_4->SetFrameBorderMode(0);
   AllExtFlights_4->SetFrameBorderMode(0);
   
   TH1D *StraightTracks = new TH1D("StraightTracks","StraightTracks",500,0,5000);
   StraightTracks->SetBinContent(21,1);
   StraightTracks->SetBinContent(22,1);
   StraightTracks->SetBinContent(24,3);
   StraightTracks->SetBinContent(25,5);
   StraightTracks->SetBinContent(26,4);
   StraightTracks->SetBinContent(27,9);
   StraightTracks->SetBinContent(28,15);
   StraightTracks->SetBinContent(29,9);
   StraightTracks->SetBinContent(30,18);
   StraightTracks->SetBinContent(31,18);
   StraightTracks->SetBinContent(32,16);
   StraightTracks->SetBinContent(33,16);
   StraightTracks->SetBinContent(34,18);
   StraightTracks->SetBinContent(35,17);
   StraightTracks->SetBinContent(36,16);
   StraightTracks->SetBinContent(37,20);
   StraightTracks->SetBinContent(38,18);
   StraightTracks->SetBinContent(39,18);
   StraightTracks->SetBinContent(40,12);
   StraightTracks->SetBinContent(41,13);
   StraightTracks->SetBinContent(42,8);
   StraightTracks->SetBinContent(43,17);
   StraightTracks->SetBinContent(44,17);
   StraightTracks->SetBinContent(45,16);
   StraightTracks->SetBinContent(46,16);
   StraightTracks->SetBinContent(47,11);
   StraightTracks->SetBinContent(48,12);
   StraightTracks->SetBinContent(49,13);
   StraightTracks->SetBinContent(50,15);
   StraightTracks->SetBinContent(51,11);
   StraightTracks->SetBinContent(52,8);
   StraightTracks->SetBinContent(53,7);
   StraightTracks->SetBinContent(54,9);
   StraightTracks->SetBinContent(55,10);
   StraightTracks->SetBinContent(56,12);
   StraightTracks->SetBinContent(57,6);
   StraightTracks->SetBinContent(58,6);
   StraightTracks->SetBinContent(59,9);
   StraightTracks->SetBinContent(60,7);
   StraightTracks->SetBinContent(61,11);
   StraightTracks->SetBinContent(62,7);
   StraightTracks->SetBinContent(63,7);
   StraightTracks->SetBinContent(64,7);
   StraightTracks->SetBinContent(65,11);
   StraightTracks->SetBinContent(66,5);
   StraightTracks->SetBinContent(67,3);
   StraightTracks->SetBinContent(68,4);
   StraightTracks->SetBinContent(69,5);
   StraightTracks->SetBinContent(70,5);
   StraightTracks->SetBinContent(71,4);
   StraightTracks->SetBinContent(72,3);
   StraightTracks->SetBinContent(73,5);
   StraightTracks->SetBinContent(74,2);
   StraightTracks->SetBinContent(75,3);
   StraightTracks->SetBinContent(76,4);
   StraightTracks->SetBinContent(77,4);
   StraightTracks->SetBinContent(78,3);
   StraightTracks->SetBinContent(79,5);
   StraightTracks->SetBinContent(80,2);
   StraightTracks->SetBinContent(81,5);
   StraightTracks->SetBinContent(82,3);
   StraightTracks->SetBinContent(83,2);
   StraightTracks->SetBinContent(84,1);
   StraightTracks->SetBinContent(85,3);
   StraightTracks->SetBinContent(86,3);
   StraightTracks->SetBinContent(87,1);
   StraightTracks->SetBinContent(89,3);
   StraightTracks->SetBinContent(90,1);
   StraightTracks->SetBinContent(91,3);
   StraightTracks->SetBinContent(92,8);
   StraightTracks->SetBinContent(93,1);
   StraightTracks->SetBinContent(95,4);
   StraightTracks->SetBinContent(96,3);
   StraightTracks->SetBinContent(98,1);
   StraightTracks->SetBinContent(99,1);
   StraightTracks->SetBinContent(100,2);
   StraightTracks->SetBinContent(101,1);
   StraightTracks->SetBinContent(102,4);
   StraightTracks->SetBinContent(103,1);
   StraightTracks->SetBinContent(105,2);
   StraightTracks->SetBinContent(106,1);
   StraightTracks->SetBinContent(107,1);
   StraightTracks->SetBinContent(108,3);
   StraightTracks->SetBinContent(109,1);
   StraightTracks->SetBinContent(111,2);
   StraightTracks->SetBinContent(113,1);
   StraightTracks->SetBinContent(114,1);
   StraightTracks->SetBinContent(115,2);
   StraightTracks->SetBinContent(116,1);
   StraightTracks->SetBinContent(119,1);
   StraightTracks->SetBinContent(122,1);
   StraightTracks->SetBinContent(124,1);
   StraightTracks->SetBinContent(127,1);
   StraightTracks->SetBinContent(130,1);
   StraightTracks->SetBinContent(136,1);
   StraightTracks->SetBinContent(143,1);
   StraightTracks->SetBinContent(145,1);
   StraightTracks->SetBinContent(156,1);
   StraightTracks->SetBinContent(171,1);
   StraightTracks->SetBinContent(179,1);
   StraightTracks->SetBinContent(189,1);
   StraightTracks->SetBinContent(197,1);
   StraightTracks->SetBinContent(199,1);
   StraightTracks->SetBinContent(205,1);
   StraightTracks->SetBinContent(214,1);
   StraightTracks->SetBinContent(235,1);
   StraightTracks->SetBinContent(301,1);
   StraightTracks->SetBinContent(352,1);
   StraightTracks->SetBinContent(426,1);
   StraightTracks->SetBinContent(501,3322);
   StraightTracks->SetEntries(2803);
   
   ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   text = ptstats->AddText("StraightTracks");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 2803   ");
   text = ptstats->AddText("Mean  =  550.8");
   text = ptstats->AddText("RMS   =    347");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   StraightTracks->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(StraightTracks);

   ci = TColor::GetColor("#ff0033");
   StraightTracks->SetLineColor(ci);

   ci = TColor::GetColor("#ff0033");
   StraightTracks->SetMarkerColor(ci);
   StraightTracks->SetMarkerStyle(25);
   StraightTracks->GetXaxis()->SetTitle("E [keV]");
   StraightTracks->GetXaxis()->SetLabelFont(42);
   StraightTracks->GetXaxis()->SetLabelSize(0.035);
   StraightTracks->GetXaxis()->SetTitleSize(0.035);
   StraightTracks->GetXaxis()->SetTitleFont(42);
   StraightTracks->GetYaxis()->SetTitle("events");
   StraightTracks->GetYaxis()->SetLabelFont(42);
   StraightTracks->GetYaxis()->SetLabelSize(0.035);
   StraightTracks->GetYaxis()->SetTitleSize(0.035);
   StraightTracks->GetYaxis()->SetTitleFont(42);
   StraightTracks->GetZaxis()->SetLabelFont(42);
   StraightTracks->GetZaxis()->SetLabelSize(0.035);
   StraightTracks->GetZaxis()->SetTitleSize(0.035);
   StraightTracks->GetZaxis()->SetTitleFont(42);
   StraightTracks->Draw("colz");
   AllExtFlights_4->Modified();
   AllExtFlights->cd();
  
// ------------>Primitives in pad: AllExtFlights_5
   AllExtFlights_5 = new TPad("AllExtFlights_5", "AllExtFlights_5",0.3433333,0.01,0.6566667,0.49);
   AllExtFlights_5->Draw();
   AllExtFlights_5->cd();
   AllExtFlights_5->Range(-3000,-0.6250243,17000,1.534938);
   AllExtFlights_5->SetFillColor(0);
   AllExtFlights_5->SetBorderMode(0);
   AllExtFlights_5->SetBorderSize(2);
   AllExtFlights_5->SetLogy();
   AllExtFlights_5->SetGridx();
   AllExtFlights_5->SetGridy();
   AllExtFlights_5->SetLeftMargin(0.15);
   AllExtFlights_5->SetBottomMargin(0.15);
   AllExtFlights_5->SetFrameBorderMode(0);
   AllExtFlights_5->SetFrameBorderMode(0);
   
   TH1D *HeavyTracks = new TH1D("HeavyTracks","HeavyTracks",100,0,15000);
   HeavyTracks->SetBinContent(4,1);
   HeavyTracks->SetBinContent(5,2);
   HeavyTracks->SetBinContent(6,3);
   HeavyTracks->SetBinContent(7,3);
   HeavyTracks->SetBinContent(8,5);
   HeavyTracks->SetBinContent(9,4);
   HeavyTracks->SetBinContent(10,7);
   HeavyTracks->SetBinContent(11,11);
   HeavyTracks->SetBinContent(12,10);
   HeavyTracks->SetBinContent(13,9);
   HeavyTracks->SetBinContent(14,3);
   HeavyTracks->SetBinContent(15,7);
   HeavyTracks->SetBinContent(16,1);
   HeavyTracks->SetBinContent(17,6);
   HeavyTracks->SetBinContent(18,3);
   HeavyTracks->SetBinContent(19,2);
   HeavyTracks->SetBinContent(20,7);
   HeavyTracks->SetBinContent(21,4);
   HeavyTracks->SetBinContent(22,2);
   HeavyTracks->SetBinContent(23,3);
   HeavyTracks->SetBinContent(24,4);
   HeavyTracks->SetBinContent(25,3);
   HeavyTracks->SetBinContent(26,2);
   HeavyTracks->SetBinContent(27,2);
   HeavyTracks->SetBinContent(28,4);
   HeavyTracks->SetBinContent(30,1);
   HeavyTracks->SetBinContent(31,1);
   HeavyTracks->SetBinContent(32,1);
   HeavyTracks->SetBinContent(33,1);
   HeavyTracks->SetBinContent(36,1);
   HeavyTracks->SetBinContent(37,2);
   HeavyTracks->SetBinContent(38,3);
   HeavyTracks->SetBinContent(40,1);
   HeavyTracks->SetBinContent(44,2);
   HeavyTracks->SetBinContent(46,1);
   HeavyTracks->SetBinContent(48,1);
   HeavyTracks->SetBinContent(52,1);
   HeavyTracks->SetBinContent(55,1);
   HeavyTracks->SetBinContent(58,1);
   HeavyTracks->SetBinContent(62,1);
   HeavyTracks->SetBinContent(75,1);
   HeavyTracks->SetBinContent(79,1);
   HeavyTracks->SetBinContent(97,1);
   HeavyTracks->SetBinContent(100,8);
   HeavyTracks->SetBinContent(101,738);
   HeavyTracks->SetEntries(848);
   
   ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   text = ptstats->AddText("HeavyTracks");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 848    ");
   text = ptstats->AddText("Mean  =   3720");
   text = ptstats->AddText("RMS   =   3560");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   HeavyTracks->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(HeavyTracks);
   HeavyTracks->SetLineColor(2);
   HeavyTracks->SetMarkerColor(2);
   HeavyTracks->SetMarkerStyle(26);
   HeavyTracks->GetXaxis()->SetTitle("E [keV]");
   HeavyTracks->GetXaxis()->SetLabelFont(42);
   HeavyTracks->GetXaxis()->SetLabelSize(0.035);
   HeavyTracks->GetXaxis()->SetTitleSize(0.035);
   HeavyTracks->GetXaxis()->SetTitleFont(42);
   HeavyTracks->GetYaxis()->SetTitle("events");
   HeavyTracks->GetYaxis()->SetLabelFont(42);
   HeavyTracks->GetYaxis()->SetLabelSize(0.035);
   HeavyTracks->GetYaxis()->SetTitleSize(0.035);
   HeavyTracks->GetYaxis()->SetTitleFont(42);
   HeavyTracks->GetZaxis()->SetLabelFont(42);
   HeavyTracks->GetZaxis()->SetLabelSize(0.035);
   HeavyTracks->GetZaxis()->SetTitleSize(0.035);
   HeavyTracks->GetZaxis()->SetTitleFont(42);
   HeavyTracks->Draw("colz");
   AllExtFlights_5->Modified();
   AllExtFlights->cd();
  
// ------------>Primitives in pad: AllExtFlights_6
   AllExtFlights_6 = new TPad("AllExtFlights_6", "AllExtFlights_6",0.6766667,0.01,0.99,0.49);
   AllExtFlights_6->Draw();
   AllExtFlights_6->cd();
   AllExtFlights_6->Range(-3000,-1.124661,17000,4.366214);
   AllExtFlights_6->SetFillColor(0);
   AllExtFlights_6->SetBorderMode(0);
   AllExtFlights_6->SetBorderSize(2);
   AllExtFlights_6->SetLogy();
   AllExtFlights_6->SetGridx();
   AllExtFlights_6->SetGridy();
   AllExtFlights_6->SetLeftMargin(0.15);
   AllExtFlights_6->SetBottomMargin(0.15);
   AllExtFlights_6->SetFrameBorderMode(0);
   AllExtFlights_6->SetFrameBorderMode(0);
   
   TH1D *SmallBlobs = new TH1D("SmallBlobs","SmallBlobs",100,0,15000);
   SmallBlobs->SetBinContent(1,3464);
   SmallBlobs->SetBinContent(2,454);
   SmallBlobs->SetBinContent(3,36);
   SmallBlobs->SetBinContent(4,9);
   SmallBlobs->SetBinContent(5,5);
   SmallBlobs->SetBinContent(6,1);
   SmallBlobs->SetBinContent(7,2);
   SmallBlobs->SetBinContent(30,1);
   SmallBlobs->SetBinContent(31,2);
   SmallBlobs->SetBinContent(32,2);
   SmallBlobs->SetBinContent(35,1);
   SmallBlobs->SetBinContent(101,19690);
   SmallBlobs->SetEntries(2995);
   
   ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   text = ptstats->AddText("SmallBlobs");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 2995   ");
   text = ptstats->AddText("Mean  =    107");
   text = ptstats->AddText("RMS   =  189.3");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   SmallBlobs->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(SmallBlobs);
   SmallBlobs->SetLineColor(4);
   SmallBlobs->SetMarkerColor(4);
   SmallBlobs->SetMarkerStyle(27);
   SmallBlobs->GetXaxis()->SetTitle("E [keV]");
   SmallBlobs->GetXaxis()->SetLabelFont(42);
   SmallBlobs->GetXaxis()->SetLabelSize(0.035);
   SmallBlobs->GetXaxis()->SetTitleSize(0.035);
   SmallBlobs->GetXaxis()->SetTitleFont(42);
   SmallBlobs->GetYaxis()->SetTitle("events");
   SmallBlobs->GetYaxis()->SetLabelFont(42);
   SmallBlobs->GetYaxis()->SetLabelSize(0.035);
   SmallBlobs->GetYaxis()->SetTitleSize(0.035);
   SmallBlobs->GetYaxis()->SetTitleFont(42);
   SmallBlobs->GetZaxis()->SetLabelFont(42);
   SmallBlobs->GetZaxis()->SetLabelSize(0.035);
   SmallBlobs->GetZaxis()->SetTitleSize(0.035);
   SmallBlobs->GetZaxis()->SetTitleFont(42);
   SmallBlobs->Draw("colz");
   AllExtFlights_6->Modified();
   AllExtFlights->cd();
   AllExtFlights->Modified();
   AllExtFlights->cd();
   AllExtFlights->SetSelected(AllExtFlights);
}
