void Americium_Spectra()
{
//=========Macro generated from canvas: Americium_Spectra/Americium_Spectra
//=========  (Sat Nov 27 19:07:42 2021) by ROOT version 6.24/06
   TCanvas *Americium_Spectra = new TCanvas("Americium_Spectra", "Americium_Spectra",0,64,1200,500);
   Americium_Spectra->SetHighLightColor(2);
   Americium_Spectra->Range(0,0,1,1);
   Americium_Spectra->SetFillColor(0);
   Americium_Spectra->SetBorderMode(0);
   Americium_Spectra->SetBorderSize(2);
   Americium_Spectra->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: Americium_Spectra_1
   TPad *Americium_Spectra_1 = new TPad("Americium_Spectra_1", "Americium_Spectra_1",0.01,0.01,0.3233333,0.99);
   Americium_Spectra_1->Draw();
   Americium_Spectra_1->cd();
   Americium_Spectra_1->Range(-375,-0.9301706,3375,3.038629);
   Americium_Spectra_1->SetFillColor(0);
   Americium_Spectra_1->SetBorderMode(0);
   Americium_Spectra_1->SetBorderSize(2);
   Americium_Spectra_1->SetLogy();
   Americium_Spectra_1->SetGridx();
   Americium_Spectra_1->SetGridy();
   Americium_Spectra_1->SetFrameBorderMode(0);
   Americium_Spectra_1->SetFrameBorderMode(0);
   
   TH1D *Dots = new TH1D("Dots","Dots",100,0,3000);
   Dots->SetBinContent(1,188);
   Dots->SetBinContent(2,91);
   Dots->SetBinContent(3,95);
   Dots->SetBinContent(4,18);
   Dots->SetBinContent(5,6);
   Dots->SetBinContent(6,2);
   Dots->SetBinContent(7,2);
   Dots->SetBinContent(9,1);
   Dots->SetBinError(1,43.31282);
   Dots->SetBinError(2,20.02498);
   Dots->SetBinError(3,20.56696);
   Dots->SetBinError(4,5.291503);
   Dots->SetBinError(5,2.44949);
   Dots->SetBinError(6,1.414214);
   Dots->SetBinError(7,1.414214);
   Dots->SetBinError(9,1);
   Dots->SetEntries(104);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *ptstats_LaTex = ptstats->AddText("Dots");
   ptstats_LaTex->SetTextSize(0.0368);
   ptstats_LaTex = ptstats->AddText("Entries = 104    ");
   ptstats_LaTex = ptstats->AddText("Mean  =   42.6");
   ptstats_LaTex = ptstats->AddText("Std Dev   =  34.99");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   Dots->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(Dots);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#0000ff");
   Dots->SetLineColor(ci);

   ci = TColor::GetColor("#0000ff");
   Dots->SetMarkerColor(ci);
   Dots->SetMarkerStyle(20);
   Dots->GetXaxis()->SetTitle("E [keV]");
   Dots->GetXaxis()->SetLabelFont(42);
   Dots->GetXaxis()->SetTitleOffset(1);
   Dots->GetXaxis()->SetTitleFont(42);
   Dots->GetYaxis()->SetTitle("Events");
   Dots->GetYaxis()->SetLabelFont(42);
   Dots->GetYaxis()->SetTitleFont(42);
   Dots->GetZaxis()->SetLabelFont(42);
   Dots->GetZaxis()->SetTitleOffset(1);
   Dots->GetZaxis()->SetTitleFont(42);
   Dots->Draw("colz");
   
   TPaveText *pt = new TPaveText(0.4340557,0.94,0.5659443,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   TText *pt_LaTex = pt->AddText("Dots");
   pt->Draw();
   Americium_Spectra_1->Modified();
   Americium_Spectra->cd();
  
// ------------>Primitives in pad: Americium_Spectra_2
   TPad *Americium_Spectra_2 = new TPad("Americium_Spectra_2", "Americium_Spectra_2",0.3433333,0.01,0.6566667,0.99);
   Americium_Spectra_2->Draw();
   Americium_Spectra_2->cd();
   Americium_Spectra_2->Range(-187.5,-0.6524382,1687.5,2.861644);
   Americium_Spectra_2->SetFillColor(0);
   Americium_Spectra_2->SetBorderMode(0);
   Americium_Spectra_2->SetBorderSize(2);
   Americium_Spectra_2->SetLogy();
   Americium_Spectra_2->SetGridx();
   Americium_Spectra_2->SetGridy();
   Americium_Spectra_2->SetFrameBorderMode(0);
   Americium_Spectra_2->SetFrameBorderMode(0);
   
   TH1D *SmallBlobs = new TH1D("SmallBlobs","SmallBlobs",100,0,1500);
   SmallBlobs->SetBinContent(2,14);
   SmallBlobs->SetBinContent(3,24);
   SmallBlobs->SetBinContent(4,29);
   SmallBlobs->SetBinContent(5,129);
   SmallBlobs->SetBinContent(6,134);
   SmallBlobs->SetBinContent(7,72);
   SmallBlobs->SetBinContent(8,49);
   SmallBlobs->SetBinContent(9,21);
   SmallBlobs->SetBinContent(10,22);
   SmallBlobs->SetBinContent(11,25);
   SmallBlobs->SetBinContent(12,9);
   SmallBlobs->SetBinContent(13,5);
   SmallBlobs->SetBinContent(14,9);
   SmallBlobs->SetBinContent(15,4);
   SmallBlobs->SetBinContent(16,4);
   SmallBlobs->SetBinContent(17,6);
   SmallBlobs->SetBinContent(19,1);
   SmallBlobs->SetBinContent(20,1);
   SmallBlobs->SetBinContent(21,1);
   SmallBlobs->SetBinContent(22,1);
   SmallBlobs->SetBinContent(23,1);
   SmallBlobs->SetBinContent(25,1);
   SmallBlobs->SetBinContent(26,1);
   SmallBlobs->SetBinContent(37,1);
   SmallBlobs->SetBinContent(41,1);
   SmallBlobs->SetBinContent(43,1);
   SmallBlobs->SetBinContent(101,1);
   SmallBlobs->SetBinError(2,5.291503);
   SmallBlobs->SetBinError(3,8.944272);
   SmallBlobs->SetBinError(4,8.660254);
   SmallBlobs->SetBinError(5,36.26293);
   SmallBlobs->SetBinError(6,36.87818);
   SmallBlobs->SetBinError(7,19.89975);
   SmallBlobs->SetBinError(8,15.71623);
   SmallBlobs->SetBinError(9,7.549834);
   SmallBlobs->SetBinError(10,6.928203);
   SmallBlobs->SetBinError(11,7.81025);
   SmallBlobs->SetBinError(12,3);
   SmallBlobs->SetBinError(13,2.236068);
   SmallBlobs->SetBinError(14,3.872983);
   SmallBlobs->SetBinError(15,2);
   SmallBlobs->SetBinError(16,2.44949);
   SmallBlobs->SetBinError(17,2.828427);
   SmallBlobs->SetBinError(19,1);
   SmallBlobs->SetBinError(20,1);
   SmallBlobs->SetBinError(21,1);
   SmallBlobs->SetBinError(22,1);
   SmallBlobs->SetBinError(23,1);
   SmallBlobs->SetBinError(25,1);
   SmallBlobs->SetBinError(26,1);
   SmallBlobs->SetBinError(37,1);
   SmallBlobs->SetBinError(41,1);
   SmallBlobs->SetBinError(43,1);
   SmallBlobs->SetBinError(101,1);
   SmallBlobs->SetEntries(168);
   
   ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   ptstats_LaTex = ptstats->AddText("SmallBlobs");
   ptstats_LaTex->SetTextSize(0.0368);
   ptstats_LaTex = ptstats->AddText("Entries = 168    ");
   ptstats_LaTex = ptstats->AddText("Mean  =  99.16");
   ptstats_LaTex = ptstats->AddText("Std Dev   =  60.85");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   SmallBlobs->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(SmallBlobs);

   ci = TColor::GetColor("#009900");
   SmallBlobs->SetLineColor(ci);

   ci = TColor::GetColor("#009900");
   SmallBlobs->SetMarkerColor(ci);
   SmallBlobs->SetMarkerStyle(21);
   SmallBlobs->GetXaxis()->SetTitle("E [keV]");
   SmallBlobs->GetXaxis()->SetLabelFont(42);
   SmallBlobs->GetXaxis()->SetTitleOffset(1);
   SmallBlobs->GetXaxis()->SetTitleFont(42);
   SmallBlobs->GetYaxis()->SetTitle("Events");
   SmallBlobs->GetYaxis()->SetLabelFont(42);
   SmallBlobs->GetYaxis()->SetTitleFont(42);
   SmallBlobs->GetZaxis()->SetLabelFont(42);
   SmallBlobs->GetZaxis()->SetTitleOffset(1);
   SmallBlobs->GetZaxis()->SetTitleFont(42);
   SmallBlobs->Draw("colz");
   
   pt = new TPaveText(0.3528033,0.94,0.6471967,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   pt_LaTex = pt->AddText("SmallBlobs");
   pt->Draw();
   Americium_Spectra_2->Modified();
   Americium_Spectra->cd();
  
// ------------>Primitives in pad: Americium_Spectra_3
   TPad *Americium_Spectra_3 = new TPad("Americium_Spectra_3", "Americium_Spectra_3",0.6766667,0.01,0.99,0.99);
   Americium_Spectra_3->Draw();
   Americium_Spectra_3->cd();
   Americium_Spectra_3->Range(-1875,-0.8192858,16875,2.040665);
   Americium_Spectra_3->SetFillColor(0);
   Americium_Spectra_3->SetBorderMode(0);
   Americium_Spectra_3->SetBorderSize(2);
   Americium_Spectra_3->SetLogy();
   Americium_Spectra_3->SetGridx();
   Americium_Spectra_3->SetGridy();
   Americium_Spectra_3->SetFrameBorderMode(0);
   Americium_Spectra_3->SetFrameBorderMode(0);
   
   TH1D *StraightTracks = new TH1D("StraightTracks","StraightTracks",100,0,15000);
   StraightTracks->SetBinContent(2,7);
   StraightTracks->SetBinContent(3,25);
   StraightTracks->SetBinContent(4,13);
   StraightTracks->SetBinContent(5,5);
   StraightTracks->SetBinContent(6,4);
   StraightTracks->SetBinContent(7,3);
   StraightTracks->SetBinContent(8,1);
   StraightTracks->SetBinContent(9,2);
   StraightTracks->SetBinContent(11,1);
   StraightTracks->SetBinContent(28,1);
   StraightTracks->SetBinError(2,2.645751);
   StraightTracks->SetBinError(3,5);
   StraightTracks->SetBinError(4,3.605551);
   StraightTracks->SetBinError(5,2.236068);
   StraightTracks->SetBinError(6,2);
   StraightTracks->SetBinError(7,2.236068);
   StraightTracks->SetBinError(8,1);
   StraightTracks->SetBinError(9,1.414214);
   StraightTracks->SetBinError(11,1);
   StraightTracks->SetBinError(28,1);
   StraightTracks->SetEntries(61);
   
   ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   ptstats_LaTex = ptstats->AddText("StraightTracks");
   ptstats_LaTex->SetTextSize(0.0368);
   ptstats_LaTex = ptstats->AddText("Entries = 61     ");
   ptstats_LaTex = ptstats->AddText("Mean  =  593.9");
   ptstats_LaTex = ptstats->AddText("Std Dev   =    525");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   StraightTracks->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(StraightTracks);
   StraightTracks->SetMarkerStyle(25);
   StraightTracks->GetXaxis()->SetTitle("E [keV]");
   StraightTracks->GetXaxis()->SetLabelFont(42);
   StraightTracks->GetXaxis()->SetTitleOffset(1);
   StraightTracks->GetXaxis()->SetTitleFont(42);
   StraightTracks->GetYaxis()->SetTitle("Events");
   StraightTracks->GetYaxis()->SetLabelFont(42);
   StraightTracks->GetYaxis()->SetTitleFont(42);
   StraightTracks->GetZaxis()->SetLabelFont(42);
   StraightTracks->GetZaxis()->SetTitleOffset(1);
   StraightTracks->GetZaxis()->SetTitleFont(42);
   StraightTracks->Draw("colz");
   
   pt = new TPaveText(0.312843,0.94,0.687157,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   pt_LaTex = pt->AddText("StraightTracks");
   pt->Draw();
   Americium_Spectra_3->Modified();
   Americium_Spectra->cd();
   Americium_Spectra->Modified();
   Americium_Spectra->cd();
   Americium_Spectra->SetSelected(Americium_Spectra);
}
