{
//=========Macro generated from canvas: MuSearchAll/MuSearchAll
//=========  (Mon Oct 30 08:09:36 2017) by ROOT version5.34/14
   TCanvas *MuSearchAll = new TCanvas("MuSearchAll", "MuSearchAll",0,50,1200,500);
   gStyle->SetOptTitle(0);
   MuSearchAll->SetHighLightColor(2);
   MuSearchAll->Range(0,0,1,1);
   MuSearchAll->SetFillColor(0);
   MuSearchAll->SetBorderMode(0);
   MuSearchAll->SetBorderSize(2);
   MuSearchAll->SetLeftMargin(0.15);
   MuSearchAll->SetBottomMargin(0.15);
   MuSearchAll->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: MuSearchAll_1
   TPad *MuSearchAll_1 = new TPad("MuSearchAll_1", "MuSearchAll_1",0.01,0.51,0.3233333,0.99);
   MuSearchAll_1->Draw();
   MuSearchAll_1->cd();
   MuSearchAll_1->Range(-75,-1.144324,425,4.477635);
   MuSearchAll_1->SetFillColor(0);
   MuSearchAll_1->SetBorderMode(0);
   MuSearchAll_1->SetBorderSize(2);
   MuSearchAll_1->SetLogy();
   MuSearchAll_1->SetGridx();
   MuSearchAll_1->SetGridy();
   MuSearchAll_1->SetLeftMargin(0.15);
   MuSearchAll_1->SetBottomMargin(0.15);
   MuSearchAll_1->SetFrameBorderMode(0);
   MuSearchAll_1->SetFrameBorderMode(0);
   
   TH1D *Dots = new TH1D("Dots","Dots",100,0,375);
   Dots->SetBinContent(2,4344);
   Dots->SetBinContent(3,2942);
   Dots->SetBinContent(4,1988);
   Dots->SetBinContent(5,2335);
   Dots->SetBinContent(6,1993);
   Dots->SetBinContent(7,1533);
   Dots->SetBinContent(8,1147);
   Dots->SetBinContent(9,1270);
   Dots->SetBinContent(10,894);
   Dots->SetBinContent(11,895);
   Dots->SetBinContent(12,683);
   Dots->SetBinContent(13,749);
   Dots->SetBinContent(14,793);
   Dots->SetBinContent(15,641);
   Dots->SetBinContent(16,477);
   Dots->SetBinContent(17,748);
   Dots->SetBinContent(18,571);
   Dots->SetBinContent(19,547);
   Dots->SetBinContent(20,393);
   Dots->SetBinContent(21,410);
   Dots->SetBinContent(22,380);
   Dots->SetBinContent(23,334);
   Dots->SetBinContent(24,227);
   Dots->SetBinContent(25,296);
   Dots->SetBinContent(26,200);
   Dots->SetBinContent(27,179);
   Dots->SetBinContent(28,113);
   Dots->SetBinContent(29,164);
   Dots->SetBinContent(30,110);
   Dots->SetBinContent(31,104);
   Dots->SetBinContent(32,69);
   Dots->SetBinContent(33,94);
   Dots->SetBinContent(34,80);
   Dots->SetBinContent(35,54);
   Dots->SetBinContent(36,38);
   Dots->SetBinContent(37,48);
   Dots->SetBinContent(38,32);
   Dots->SetBinContent(39,27);
   Dots->SetBinContent(40,25);
   Dots->SetBinContent(41,19);
   Dots->SetBinContent(42,23);
   Dots->SetBinContent(43,18);
   Dots->SetBinContent(44,11);
   Dots->SetBinContent(45,19);
   Dots->SetBinContent(46,14);
   Dots->SetBinContent(47,5);
   Dots->SetBinContent(48,3);
   Dots->SetBinContent(49,8);
   Dots->SetBinContent(50,6);
   Dots->SetBinContent(51,3);
   Dots->SetBinContent(52,3);
   Dots->SetBinContent(53,1);
   Dots->SetBinContent(54,1);
   Dots->SetBinContent(55,1);
   Dots->SetBinContent(56,2);
   Dots->SetBinContent(57,1);
   Dots->SetBinContent(59,4);
   Dots->SetBinContent(60,1);
   Dots->SetBinContent(62,1);
   Dots->SetBinContent(64,1);
   Dots->SetBinContent(65,1);
   Dots->SetBinContent(66,2);
   Dots->SetBinContent(67,2);
   Dots->SetBinContent(68,2);
   Dots->SetBinContent(69,3);
   Dots->SetBinContent(70,2);
   Dots->SetBinContent(71,1);
   Dots->SetBinContent(72,1);
   Dots->SetBinContent(74,3);
   Dots->SetBinContent(75,1);
   Dots->SetBinContent(76,1);
   Dots->SetBinContent(77,1);
   Dots->SetBinContent(78,2);
   Dots->SetBinContent(79,2);
   Dots->SetBinContent(80,1);
   Dots->SetBinContent(82,2);
   Dots->SetBinContent(83,1);
   Dots->SetBinContent(84,1);
   Dots->SetBinContent(85,2);
   Dots->SetBinContent(86,1);
   Dots->SetBinContent(88,1);
   Dots->SetBinContent(90,2);
   Dots->SetBinContent(92,2);
   Dots->SetBinContent(93,3);
   Dots->SetBinContent(97,1);
   Dots->SetBinContent(98,1);
   Dots->SetBinContent(99,1);
   Dots->SetBinContent(101,22723);
   Dots->SetEntries(745);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("Dots");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 745    ");
   text = ptstats->AddText("Mean  =  34.69");
   text = ptstats->AddText("RMS   =  32.15");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   Dots->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(Dots);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#00cc66");
   Dots->SetLineColor(ci);

   ci = TColor::GetColor("#00cc66");
   Dots->SetMarkerColor(ci);
   Dots->SetMarkerStyle(20);
   Dots->GetXaxis()->SetTitle("E [keV]");
   Dots->GetXaxis()->SetLabelFont(42);
   Dots->GetXaxis()->SetLabelSize(0.035);
   Dots->GetXaxis()->SetTitleSize(0.035);
   Dots->GetXaxis()->SetTitleFont(42);
   Dots->GetYaxis()->SetTitle("events");
   Dots->GetYaxis()->SetLabelFont(42);
   Dots->GetYaxis()->SetLabelSize(0.035);
   Dots->GetYaxis()->SetTitleSize(0.035);
   Dots->GetYaxis()->SetTitleFont(42);
   Dots->GetZaxis()->SetLabelFont(42);
   Dots->GetZaxis()->SetLabelSize(0.035);
   Dots->GetZaxis()->SetTitleSize(0.035);
   Dots->GetZaxis()->SetTitleFont(42);
   Dots->Draw("colz");
   MuSearchAll_1->Modified();
   MuSearchAll->cd();
  
// ------------>Primitives in pad: MuSearchAll_2
   MuSearchAll_2 = new TPad("MuSearchAll_2", "MuSearchAll_2",0.3433333,0.51,0.6566667,0.99);
   MuSearchAll_2->Draw();
   MuSearchAll_2->cd();
   MuSearchAll_2->Range(-3000,-0.5973638,17000,1.378195);
   MuSearchAll_2->SetFillColor(0);
   MuSearchAll_2->SetBorderMode(0);
   MuSearchAll_2->SetBorderSize(2);
   MuSearchAll_2->SetLogy();
   MuSearchAll_2->SetGridx();
   MuSearchAll_2->SetGridy();
   MuSearchAll_2->SetLeftMargin(0.15);
   MuSearchAll_2->SetBottomMargin(0.15);
   MuSearchAll_2->SetFrameBorderMode(0);
   MuSearchAll_2->SetFrameBorderMode(0);
   
   TH1D *HeavyBlobs = new TH1D("HeavyBlobs","HeavyBlobs",100,0,15000);
   HeavyBlobs->SetBinContent(2,6);
   HeavyBlobs->SetBinContent(3,8);
   HeavyBlobs->SetBinContent(4,3);
   HeavyBlobs->SetBinContent(7,1);
   HeavyBlobs->SetBinContent(8,1);
   HeavyBlobs->SetBinContent(10,1);
   HeavyBlobs->SetBinContent(14,1);
   HeavyBlobs->SetBinContent(23,2);
   HeavyBlobs->SetBinContent(26,1);
   HeavyBlobs->SetBinContent(27,1);
   HeavyBlobs->SetBinContent(29,2);
   HeavyBlobs->SetBinContent(32,1);
   HeavyBlobs->SetBinContent(33,3);
   HeavyBlobs->SetBinContent(34,2);
   HeavyBlobs->SetBinContent(35,1);
   HeavyBlobs->SetBinContent(37,1);
   HeavyBlobs->SetBinContent(38,1);
   HeavyBlobs->SetBinContent(39,1);
   HeavyBlobs->SetBinContent(40,1);
   HeavyBlobs->SetBinContent(43,1);
   HeavyBlobs->SetBinContent(45,1);
   HeavyBlobs->SetBinContent(46,1);
   HeavyBlobs->SetBinContent(50,1);
   HeavyBlobs->SetBinContent(51,2);
   HeavyBlobs->SetBinContent(52,1);
   HeavyBlobs->SetBinContent(53,2);
   HeavyBlobs->SetBinContent(57,1);
   HeavyBlobs->SetBinContent(59,2);
   HeavyBlobs->SetBinContent(61,1);
   HeavyBlobs->SetBinContent(101,24);
   HeavyBlobs->SetEntries(74);
   
   ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   text = ptstats->AddText("HeavyBlobs");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 74     ");
   text = ptstats->AddText("Mean  =   3774");
   text = ptstats->AddText("RMS   =   3017");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   HeavyBlobs->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(HeavyBlobs);

   ci = TColor::GetColor("#cc6600");
   HeavyBlobs->SetLineColor(ci);

   ci = TColor::GetColor("#cc6600");
   HeavyBlobs->SetMarkerColor(ci);
   HeavyBlobs->SetMarkerStyle(21);
   HeavyBlobs->GetXaxis()->SetTitle("E [keV]");
   HeavyBlobs->GetXaxis()->SetLabelFont(42);
   HeavyBlobs->GetXaxis()->SetLabelSize(0.035);
   HeavyBlobs->GetXaxis()->SetTitleSize(0.035);
   HeavyBlobs->GetXaxis()->SetTitleFont(42);
   HeavyBlobs->GetYaxis()->SetTitle("events");
   HeavyBlobs->GetYaxis()->SetLabelFont(42);
   HeavyBlobs->GetYaxis()->SetLabelSize(0.035);
   HeavyBlobs->GetYaxis()->SetTitleSize(0.035);
   HeavyBlobs->GetYaxis()->SetTitleFont(42);
   HeavyBlobs->GetZaxis()->SetLabelFont(42);
   HeavyBlobs->GetZaxis()->SetLabelSize(0.035);
   HeavyBlobs->GetZaxis()->SetTitleSize(0.035);
   HeavyBlobs->GetZaxis()->SetTitleFont(42);
   HeavyBlobs->Draw("colz");
   MuSearchAll_2->Modified();
   MuSearchAll->cd();
  
// ------------>Primitives in pad: MuSearchAll_3
   MuSearchAll_3 = new TPad("MuSearchAll_3", "MuSearchAll_3",0.6766667,0.51,0.99,0.99);
   MuSearchAll_3->Draw();
   MuSearchAll_3->cd();
   MuSearchAll_3->Range(-300,-1.016746,1700,3.754693);
   MuSearchAll_3->SetFillColor(0);
   MuSearchAll_3->SetBorderMode(0);
   MuSearchAll_3->SetBorderSize(2);
   MuSearchAll_3->SetLogy();
   MuSearchAll_3->SetGridx();
   MuSearchAll_3->SetGridy();
   MuSearchAll_3->SetLeftMargin(0.15);
   MuSearchAll_3->SetBottomMargin(0.15);
   MuSearchAll_3->SetFrameBorderMode(0);
   MuSearchAll_3->SetFrameBorderMode(0);
   
   TH1D *CurlyTracks = new TH1D("CurlyTracks","CurlyTracks",100,0,1500);
   CurlyTracks->SetBinContent(2,3);
   CurlyTracks->SetBinContent(3,22);
   CurlyTracks->SetBinContent(4,62);
   CurlyTracks->SetBinContent(5,198);
   CurlyTracks->SetBinContent(6,559);
   CurlyTracks->SetBinContent(7,968);
   CurlyTracks->SetBinContent(8,1000);
   CurlyTracks->SetBinContent(9,971);
   CurlyTracks->SetBinContent(10,892);
   CurlyTracks->SetBinContent(11,727);
   CurlyTracks->SetBinContent(12,733);
   CurlyTracks->SetBinContent(13,624);
   CurlyTracks->SetBinContent(14,723);
   CurlyTracks->SetBinContent(15,615);
   CurlyTracks->SetBinContent(16,612);
   CurlyTracks->SetBinContent(17,532);
   CurlyTracks->SetBinContent(18,493);
   CurlyTracks->SetBinContent(19,469);
   CurlyTracks->SetBinContent(20,418);
   CurlyTracks->SetBinContent(21,395);
   CurlyTracks->SetBinContent(22,325);
   CurlyTracks->SetBinContent(23,281);
   CurlyTracks->SetBinContent(24,239);
   CurlyTracks->SetBinContent(25,252);
   CurlyTracks->SetBinContent(26,213);
   CurlyTracks->SetBinContent(27,183);
   CurlyTracks->SetBinContent(28,162);
   CurlyTracks->SetBinContent(29,170);
   CurlyTracks->SetBinContent(30,121);
   CurlyTracks->SetBinContent(31,115);
   CurlyTracks->SetBinContent(32,88);
   CurlyTracks->SetBinContent(33,93);
   CurlyTracks->SetBinContent(34,80);
   CurlyTracks->SetBinContent(35,65);
   CurlyTracks->SetBinContent(36,70);
   CurlyTracks->SetBinContent(37,54);
   CurlyTracks->SetBinContent(38,53);
   CurlyTracks->SetBinContent(39,36);
   CurlyTracks->SetBinContent(40,47);
   CurlyTracks->SetBinContent(41,45);
   CurlyTracks->SetBinContent(42,40);
   CurlyTracks->SetBinContent(43,34);
   CurlyTracks->SetBinContent(44,24);
   CurlyTracks->SetBinContent(45,21);
   CurlyTracks->SetBinContent(46,21);
   CurlyTracks->SetBinContent(47,18);
   CurlyTracks->SetBinContent(48,17);
   CurlyTracks->SetBinContent(49,18);
   CurlyTracks->SetBinContent(50,17);
   CurlyTracks->SetBinContent(51,10);
   CurlyTracks->SetBinContent(52,8);
   CurlyTracks->SetBinContent(53,7);
   CurlyTracks->SetBinContent(54,14);
   CurlyTracks->SetBinContent(55,10);
   CurlyTracks->SetBinContent(56,9);
   CurlyTracks->SetBinContent(57,10);
   CurlyTracks->SetBinContent(58,6);
   CurlyTracks->SetBinContent(59,5);
   CurlyTracks->SetBinContent(60,4);
   CurlyTracks->SetBinContent(61,7);
   CurlyTracks->SetBinContent(62,2);
   CurlyTracks->SetBinContent(63,4);
   CurlyTracks->SetBinContent(64,6);
   CurlyTracks->SetBinContent(65,2);
   CurlyTracks->SetBinContent(66,4);
   CurlyTracks->SetBinContent(67,3);
   CurlyTracks->SetBinContent(68,4);
   CurlyTracks->SetBinContent(69,3);
   CurlyTracks->SetBinContent(70,4);
   CurlyTracks->SetBinContent(71,2);
   CurlyTracks->SetBinContent(72,1);
   CurlyTracks->SetBinContent(73,1);
   CurlyTracks->SetBinContent(75,3);
   CurlyTracks->SetBinContent(76,2);
   CurlyTracks->SetBinContent(77,1);
   CurlyTracks->SetBinContent(78,2);
   CurlyTracks->SetBinContent(79,1);
   CurlyTracks->SetBinContent(80,2);
   CurlyTracks->SetBinContent(82,2);
   CurlyTracks->SetBinContent(83,2);
   CurlyTracks->SetBinContent(84,1);
   CurlyTracks->SetBinContent(86,1);
   CurlyTracks->SetBinContent(87,3);
   CurlyTracks->SetBinContent(88,1);
   CurlyTracks->SetBinContent(89,1);
   CurlyTracks->SetBinContent(90,1);
   CurlyTracks->SetBinContent(91,2);
   CurlyTracks->SetBinContent(93,1);
   CurlyTracks->SetBinContent(96,2);
   CurlyTracks->SetBinContent(98,1);
   CurlyTracks->SetBinContent(100,2);
   CurlyTracks->SetBinContent(101,11049);
   CurlyTracks->SetEntries(1866);
   
   ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   text = ptstats->AddText("CurlyTracks");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 1866   ");
   text = ptstats->AddText("Mean  =  236.6");
   text = ptstats->AddText("RMS   =  149.4");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   CurlyTracks->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(CurlyTracks);

   ci = TColor::GetColor("#009900");
   CurlyTracks->SetLineColor(ci);

   ci = TColor::GetColor("#009900");
   CurlyTracks->SetMarkerColor(ci);
   CurlyTracks->SetMarkerStyle(23);
   CurlyTracks->GetXaxis()->SetTitle("E [keV]");
   CurlyTracks->GetXaxis()->SetLabelFont(42);
   CurlyTracks->GetXaxis()->SetLabelSize(0.035);
   CurlyTracks->GetXaxis()->SetTitleSize(0.035);
   CurlyTracks->GetXaxis()->SetTitleFont(42);
   CurlyTracks->GetYaxis()->SetTitle("events");
   CurlyTracks->GetYaxis()->SetLabelFont(42);
   CurlyTracks->GetYaxis()->SetLabelSize(0.035);
   CurlyTracks->GetYaxis()->SetTitleSize(0.035);
   CurlyTracks->GetYaxis()->SetTitleFont(42);
   CurlyTracks->GetZaxis()->SetLabelFont(42);
   CurlyTracks->GetZaxis()->SetLabelSize(0.035);
   CurlyTracks->GetZaxis()->SetTitleSize(0.035);
   CurlyTracks->GetZaxis()->SetTitleFont(42);
   CurlyTracks->Draw("colz");
   MuSearchAll_3->Modified();
   MuSearchAll->cd();
  
// ------------>Primitives in pad: MuSearchAll_4
   MuSearchAll_4 = new TPad("MuSearchAll_4", "MuSearchAll_4",0.01,0.01,0.3233333,0.49);
   MuSearchAll_4->Draw();
   MuSearchAll_4->cd();
   MuSearchAll_4->Range(-1000,-0.6890914,5666.667,1.897984);
   MuSearchAll_4->SetFillColor(0);
   MuSearchAll_4->SetBorderMode(0);
   MuSearchAll_4->SetBorderSize(2);
   MuSearchAll_4->SetLogy();
   MuSearchAll_4->SetGridx();
   MuSearchAll_4->SetGridy();
   MuSearchAll_4->SetLeftMargin(0.15);
   MuSearchAll_4->SetBottomMargin(0.15);
   MuSearchAll_4->SetFrameBorderMode(0);
   MuSearchAll_4->SetFrameBorderMode(0);
   
   TH1D *StraightTracks = new TH1D("StraightTracks","StraightTracks",500,0,5000);
   StraightTracks->SetBinContent(21,1);
   StraightTracks->SetBinContent(24,2);
   StraightTracks->SetBinContent(25,4);
   StraightTracks->SetBinContent(26,6);
   StraightTracks->SetBinContent(27,8);
   StraightTracks->SetBinContent(28,14);
   StraightTracks->SetBinContent(29,7);
   StraightTracks->SetBinContent(30,22);
   StraightTracks->SetBinContent(31,15);
   StraightTracks->SetBinContent(32,16);
   StraightTracks->SetBinContent(33,19);
   StraightTracks->SetBinContent(34,11);
   StraightTracks->SetBinContent(35,19);
   StraightTracks->SetBinContent(36,13);
   StraightTracks->SetBinContent(37,23);
   StraightTracks->SetBinContent(38,23);
   StraightTracks->SetBinContent(39,21);
   StraightTracks->SetBinContent(40,17);
   StraightTracks->SetBinContent(41,16);
   StraightTracks->SetBinContent(42,19);
   StraightTracks->SetBinContent(43,20);
   StraightTracks->SetBinContent(44,13);
   StraightTracks->SetBinContent(45,9);
   StraightTracks->SetBinContent(46,14);
   StraightTracks->SetBinContent(47,5);
   StraightTracks->SetBinContent(48,11);
   StraightTracks->SetBinContent(49,9);
   StraightTracks->SetBinContent(50,14);
   StraightTracks->SetBinContent(51,7);
   StraightTracks->SetBinContent(52,7);
   StraightTracks->SetBinContent(53,9);
   StraightTracks->SetBinContent(54,4);
   StraightTracks->SetBinContent(55,12);
   StraightTracks->SetBinContent(56,8);
   StraightTracks->SetBinContent(57,3);
   StraightTracks->SetBinContent(58,7);
   StraightTracks->SetBinContent(59,4);
   StraightTracks->SetBinContent(60,3);
   StraightTracks->SetBinContent(61,6);
   StraightTracks->SetBinContent(62,4);
   StraightTracks->SetBinContent(63,4);
   StraightTracks->SetBinContent(64,3);
   StraightTracks->SetBinContent(65,6);
   StraightTracks->SetBinContent(66,4);
   StraightTracks->SetBinContent(67,1);
   StraightTracks->SetBinContent(68,5);
   StraightTracks->SetBinContent(69,1);
   StraightTracks->SetBinContent(70,4);
   StraightTracks->SetBinContent(71,3);
   StraightTracks->SetBinContent(73,4);
   StraightTracks->SetBinContent(74,2);
   StraightTracks->SetBinContent(75,2);
   StraightTracks->SetBinContent(76,3);
   StraightTracks->SetBinContent(77,3);
   StraightTracks->SetBinContent(78,3);
   StraightTracks->SetBinContent(79,4);
   StraightTracks->SetBinContent(80,1);
   StraightTracks->SetBinContent(83,1);
   StraightTracks->SetBinContent(84,1);
   StraightTracks->SetBinContent(85,2);
   StraightTracks->SetBinContent(86,2);
   StraightTracks->SetBinContent(87,2);
   StraightTracks->SetBinContent(88,2);
   StraightTracks->SetBinContent(89,6);
   StraightTracks->SetBinContent(93,2);
   StraightTracks->SetBinContent(96,1);
   StraightTracks->SetBinContent(97,1);
   StraightTracks->SetBinContent(99,1);
   StraightTracks->SetBinContent(102,2);
   StraightTracks->SetBinContent(104,1);
   StraightTracks->SetBinContent(105,2);
   StraightTracks->SetBinContent(106,2);
   StraightTracks->SetBinContent(107,3);
   StraightTracks->SetBinContent(109,2);
   StraightTracks->SetBinContent(110,1);
   StraightTracks->SetBinContent(111,1);
   StraightTracks->SetBinContent(114,1);
   StraightTracks->SetBinContent(116,2);
   StraightTracks->SetBinContent(118,1);
   StraightTracks->SetBinContent(119,1);
   StraightTracks->SetBinContent(120,2);
   StraightTracks->SetBinContent(121,2);
   StraightTracks->SetBinContent(122,1);
   StraightTracks->SetBinContent(131,1);
   StraightTracks->SetBinContent(134,1);
   StraightTracks->SetBinContent(138,1);
   StraightTracks->SetBinContent(139,1);
   StraightTracks->SetBinContent(140,1);
   StraightTracks->SetBinContent(141,1);
   StraightTracks->SetBinContent(144,1);
   StraightTracks->SetBinContent(147,1);
   StraightTracks->SetBinContent(148,1);
   StraightTracks->SetBinContent(152,1);
   StraightTracks->SetBinContent(155,1);
   StraightTracks->SetBinContent(159,1);
   StraightTracks->SetBinContent(165,1);
   StraightTracks->SetBinContent(166,1);
   StraightTracks->SetBinContent(167,1);
   StraightTracks->SetBinContent(169,2);
   StraightTracks->SetBinContent(172,2);
   StraightTracks->SetBinContent(175,2);
   StraightTracks->SetBinContent(184,1);
   StraightTracks->SetBinContent(187,1);
   StraightTracks->SetBinContent(198,1);
   StraightTracks->SetBinContent(202,1);
   StraightTracks->SetBinContent(213,1);
   StraightTracks->SetBinContent(238,1);
   StraightTracks->SetBinContent(251,1);
   StraightTracks->SetBinContent(280,1);
   StraightTracks->SetBinContent(306,1);
   StraightTracks->SetBinContent(334,1);
   StraightTracks->SetBinContent(335,1);
   StraightTracks->SetBinContent(342,1);
   StraightTracks->SetBinContent(407,1);
   StraightTracks->SetBinContent(433,1);
   StraightTracks->SetBinContent(457,1);
   StraightTracks->SetBinContent(501,309);
   StraightTracks->SetEntries(612);
   
   ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   text = ptstats->AddText("StraightTracks");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 612    ");
   text = ptstats->AddText("Mean  =  582.4");
   text = ptstats->AddText("RMS   =    493");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   StraightTracks->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(StraightTracks);

   ci = TColor::GetColor("#ff0033");
   StraightTracks->SetLineColor(ci);

   ci = TColor::GetColor("#ff0033");
   StraightTracks->SetMarkerColor(ci);
   StraightTracks->SetMarkerStyle(25);
   StraightTracks->GetXaxis()->SetTitle("E [keV]");
   StraightTracks->GetXaxis()->SetLabelFont(42);
   StraightTracks->GetXaxis()->SetLabelSize(0.035);
   StraightTracks->GetXaxis()->SetTitleSize(0.035);
   StraightTracks->GetXaxis()->SetTitleFont(42);
   StraightTracks->GetYaxis()->SetTitle("events");
   StraightTracks->GetYaxis()->SetLabelFont(42);
   StraightTracks->GetYaxis()->SetLabelSize(0.035);
   StraightTracks->GetYaxis()->SetTitleSize(0.035);
   StraightTracks->GetYaxis()->SetTitleFont(42);
   StraightTracks->GetZaxis()->SetLabelFont(42);
   StraightTracks->GetZaxis()->SetLabelSize(0.035);
   StraightTracks->GetZaxis()->SetTitleSize(0.035);
   StraightTracks->GetZaxis()->SetTitleFont(42);
   StraightTracks->Draw("colz");
   MuSearchAll_4->Modified();
   MuSearchAll->cd();
  
// ------------>Primitives in pad: MuSearchAll_5
   MuSearchAll_5 = new TPad("MuSearchAll_5", "MuSearchAll_5",0.3433333,0.01,0.6566667,0.49);
   MuSearchAll_5->Draw();
   MuSearchAll_5->cd();
   MuSearchAll_5->Range(-3000,-0.5371578,17000,1.037027);
   MuSearchAll_5->SetFillColor(0);
   MuSearchAll_5->SetBorderMode(0);
   MuSearchAll_5->SetBorderSize(2);
   MuSearchAll_5->SetLogy();
   MuSearchAll_5->SetGridx();
   MuSearchAll_5->SetGridy();
   MuSearchAll_5->SetLeftMargin(0.15);
   MuSearchAll_5->SetBottomMargin(0.15);
   MuSearchAll_5->SetFrameBorderMode(0);
   MuSearchAll_5->SetFrameBorderMode(0);
   
   TH1D *HeavyTracks = new TH1D("HeavyTracks","HeavyTracks",100,0,15000);
   HeavyTracks->SetBinContent(4,3);
   HeavyTracks->SetBinContent(5,4);
   HeavyTracks->SetBinContent(6,2);
   HeavyTracks->SetBinContent(7,1);
   HeavyTracks->SetBinContent(9,2);
   HeavyTracks->SetBinContent(10,1);
   HeavyTracks->SetBinContent(11,1);
   HeavyTracks->SetBinContent(12,1);
   HeavyTracks->SetBinContent(13,1);
   HeavyTracks->SetBinContent(21,1);
   HeavyTracks->SetBinContent(27,1);
   HeavyTracks->SetBinContent(30,1);
   HeavyTracks->SetBinContent(36,1);
   HeavyTracks->SetBinContent(40,1);
   HeavyTracks->SetBinContent(43,1);
   HeavyTracks->SetBinContent(57,1);
   HeavyTracks->SetBinContent(59,1);
   HeavyTracks->SetBinContent(60,1);
   HeavyTracks->SetBinContent(68,1);
   HeavyTracks->SetBinContent(100,1);
   HeavyTracks->SetBinContent(101,11);
   HeavyTracks->SetEntries(37);
   
   ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   text = ptstats->AddText("HeavyTracks");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 37     ");
   text = ptstats->AddText("Mean  =   3577");
   text = ptstats->AddText("RMS   =   3745");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   HeavyTracks->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(HeavyTracks);
   HeavyTracks->SetLineColor(2);
   HeavyTracks->SetMarkerColor(2);
   HeavyTracks->SetMarkerStyle(26);
   HeavyTracks->GetXaxis()->SetTitle("E [keV]");
   HeavyTracks->GetXaxis()->SetLabelFont(42);
   HeavyTracks->GetXaxis()->SetLabelSize(0.035);
   HeavyTracks->GetXaxis()->SetTitleSize(0.035);
   HeavyTracks->GetXaxis()->SetTitleFont(42);
   HeavyTracks->GetYaxis()->SetTitle("events");
   HeavyTracks->GetYaxis()->SetLabelFont(42);
   HeavyTracks->GetYaxis()->SetLabelSize(0.035);
   HeavyTracks->GetYaxis()->SetTitleSize(0.035);
   HeavyTracks->GetYaxis()->SetTitleFont(42);
   HeavyTracks->GetZaxis()->SetLabelFont(42);
   HeavyTracks->GetZaxis()->SetLabelSize(0.035);
   HeavyTracks->GetZaxis()->SetTitleSize(0.035);
   HeavyTracks->GetZaxis()->SetTitleFont(42);
   HeavyTracks->Draw("colz");
   MuSearchAll_5->Modified();
   MuSearchAll->cd();
  
// ------------>Primitives in pad: MuSearchAll_6
   MuSearchAll_6 = new TPad("MuSearchAll_6", "MuSearchAll_6",0.6766667,0.01,0.99,0.49);
   MuSearchAll_6->Draw();
   MuSearchAll_6->cd();
   MuSearchAll_6->Range(-3000,-1.225904,17000,4.939924);
   MuSearchAll_6->SetFillColor(0);
   MuSearchAll_6->SetBorderMode(0);
   MuSearchAll_6->SetBorderSize(2);
   MuSearchAll_6->SetLogy();
   MuSearchAll_6->SetGridx();
   MuSearchAll_6->SetGridy();
   MuSearchAll_6->SetLeftMargin(0.15);
   MuSearchAll_6->SetBottomMargin(0.15);
   MuSearchAll_6->SetFrameBorderMode(0);
   MuSearchAll_6->SetFrameBorderMode(0);
   
   TH1D *SmallBlobs = new TH1D("SmallBlobs","SmallBlobs",100,0,15000);
   SmallBlobs->SetBinContent(1,11112);
   SmallBlobs->SetBinContent(2,2575);
   SmallBlobs->SetBinContent(3,59);
   SmallBlobs->SetBinContent(4,6);
   SmallBlobs->SetBinContent(5,4);
   SmallBlobs->SetBinContent(6,6);
   SmallBlobs->SetBinContent(7,4);
   SmallBlobs->SetBinContent(8,6);
   SmallBlobs->SetBinContent(9,2);
   SmallBlobs->SetBinContent(10,2);
   SmallBlobs->SetBinContent(12,1);
   SmallBlobs->SetBinContent(13,3);
   SmallBlobs->SetBinContent(14,1);
   SmallBlobs->SetBinContent(15,2);
   SmallBlobs->SetBinContent(16,1);
   SmallBlobs->SetBinContent(17,4);
   SmallBlobs->SetBinContent(19,1);
   SmallBlobs->SetBinContent(20,1);
   SmallBlobs->SetBinContent(21,2);
   SmallBlobs->SetBinContent(22,2);
   SmallBlobs->SetBinContent(23,3);
   SmallBlobs->SetBinContent(24,3);
   SmallBlobs->SetBinContent(25,5);
   SmallBlobs->SetBinContent(26,9);
   SmallBlobs->SetBinContent(27,9);
   SmallBlobs->SetBinContent(28,14);
   SmallBlobs->SetBinContent(29,14);
   SmallBlobs->SetBinContent(30,18);
   SmallBlobs->SetBinContent(31,19);
   SmallBlobs->SetBinContent(32,14);
   SmallBlobs->SetBinContent(33,25);
   SmallBlobs->SetBinContent(34,9);
   SmallBlobs->SetBinContent(35,4);
   SmallBlobs->SetBinContent(36,3);
   SmallBlobs->SetBinContent(37,1);
   SmallBlobs->SetBinContent(101,11254);
   SmallBlobs->SetEntries(971);
   
   ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   text = ptstats->AddText("SmallBlobs");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 971    ");
   text = ptstats->AddText("Mean  =  154.5");
   text = ptstats->AddText("RMS   =  464.9");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   SmallBlobs->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(SmallBlobs);
   SmallBlobs->SetLineColor(4);
   SmallBlobs->SetMarkerColor(4);
   SmallBlobs->SetMarkerStyle(27);
   SmallBlobs->GetXaxis()->SetTitle("E [keV]");
   SmallBlobs->GetXaxis()->SetLabelFont(42);
   SmallBlobs->GetXaxis()->SetLabelSize(0.035);
   SmallBlobs->GetXaxis()->SetTitleSize(0.035);
   SmallBlobs->GetXaxis()->SetTitleFont(42);
   SmallBlobs->GetYaxis()->SetTitle("events");
   SmallBlobs->GetYaxis()->SetLabelFont(42);
   SmallBlobs->GetYaxis()->SetLabelSize(0.035);
   SmallBlobs->GetYaxis()->SetTitleSize(0.035);
   SmallBlobs->GetYaxis()->SetTitleFont(42);
   SmallBlobs->GetZaxis()->SetLabelFont(42);
   SmallBlobs->GetZaxis()->SetLabelSize(0.035);
   SmallBlobs->GetZaxis()->SetTitleSize(0.035);
   SmallBlobs->GetZaxis()->SetTitleFont(42);
   SmallBlobs->Draw("colz");
   MuSearchAll_6->Modified();
   MuSearchAll->cd();
   MuSearchAll->Modified();
   MuSearchAll->cd();
   MuSearchAll->SetSelected(MuSearchAll);
}
